# Generated by Django 4.2.7 on 2023-11-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0018_customuser_badge_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='badge_count',
        ),
    ]
