# Generated by Django 4.2.7 on 2023-11-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0019_remove_customuser_badge_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='badgecount',
            field=models.IntegerField(default=0, verbose_name='badge sayısı'),
        ),
    ]
