# Generated by Django 4.2.3 on 2023-10-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='tagDescription',
            field=models.TextField(max_length=100, null=True, verbose_name='Açıklma'),
        ),
        migrations.AddField(
            model_name='tags',
            name='view',
            field=models.IntegerField(default=0, verbose_name='Görüntülenme Sayısı'),
        ),
    ]
