# Generated by Django 4.2.3 on 2023-10-17 12:20

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0002_tags_tagdescription_tags_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='Açıklama')),
                ('createdAt', models.DateTimeField(auto_now=True, verbose_name='Oluşturma tarihi')),
                ('like', models.IntegerField(default=0, verbose_name='Beğeni Sayısı')),
                ('comment', models.IntegerField(default=0, verbose_name='Yorum Sayısı')),
                ('kodalanı', ckeditor.fields.RichTextField(max_length=1500, null=True, verbose_name='Kod Bloğu')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazarı')),
            ],
        ),
    ]
