# Generated by Django 4.2.5 on 2023-10-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_answerlikes_answerdislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='answerCount',
            field=models.IntegerField(default=0, verbose_name='Görüntülenme Sayısı'),
        ),
    ]
